version: '3'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=finapp
      - POSTGRES_PASSWORD=finapp123
      - POSTGRES_DB=financial_transactions
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-net
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
    
volumes:
  postgres-data:
