finance_dbt_profile:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: sunlit-pixel-456910-j0
      dataset: dbt_dev
      threads: 4
      keyfile: /home/mohamed-client/Documents/data-engineering/f/config/sunlit-pixel-456910-j0-58efdfa37d95.json
