version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:3.0.0
  build:
    context: ..
    dockerfile: ./airflow/Dockerfile
  env_file:
    - .env
  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    AIRFLOW__CELERY__RESULT_BACKEND: db+sqlite:////opt/airflow/airflow.db
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"

  volumes:
    - ../dags:/opt/airflow/dags
    - ../src:/opt/airflow/src
    - ../logs:/opt/airflow/logs
    - ../config:/opt/airflow/config
    - ../plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on: &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy
  networks:
    - de-network

services:
  spark:
    image: bitnami/spark:latest
    container_name: spark-bucket-bq
    environment:
      - SPARK_MODE=driver
    volumes:
      - ../src:/opt/spark/src
      - ../jars:/opt/spark/jars
      - ../key.json:/opt/keys/key.json
      - ../src/config.py:/opt/spark/src/config.py
      - ./requirements.txt:/opt/requirements.txt # Mount your requirements.txt into container

    command: >
      bash -c "pip install -r /opt/requirements.txt && spark-submit --jars /opt/spark/jars/gcs-connector-hadoop3-latest.jar --conf spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem --conf spark.hadoop.google.cloud.auth.service.account.enable=true --conf spark.hadoop.google.cloud.auth.service.account.json.keyfile=/opt/keys/key.json python /opt/spark/src/bucket_to_bq.py"
    depends_on:
      - airflow-webserver
    networks:
      - de-network

  redis:
    image: redis:7.2-bookworm
    container_name: redis_airflow
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - de-network

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ""
    user: "0:0"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      - de-network

  airflow-webserver:
    <<: *airflow-common
    command: api-server
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - de-network

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "http://localhost:8973/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    # restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    networks:
      - de-network

  airflow-worker:
    <<: *airflow-common
    command: airflow celery worker
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
    networks:
      - de-network

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - de-network

  flower:
    <<: *airflow-common
    command: celery flower
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - de-network

networks:
  de-network:
    driver: bridge
